spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root: warn
    com.llf: info
  file: log/blog-pro.log
server:
  port: 8888